export const PRODUCER_SERVICE = 'PRODUCER_SERVICE';
export const COLOR_SERVICE = 'COLOR_SERVICE';
export const COUNTRY_SERVICE = 'COUNTRY_SERVICE';
export const SWEET_SERVICE = 'SWEET_SERVICE';
export const VINE_SERVICE = 'VINE_SERVICE';